services:
  blog:
#    image: ${CI_REGISTRY}/${CI_PROJECT}/${CI_SERVICE}:${CI_TAG}
    image: ${CI_REGISTRY_IMAGE}:${CI_TAG}
    restart: unless-stopped
    environment:
      - BACKEND_SERVER_URL=${BACKEND_SERVER_URL} # nextjs
    networks:
      - app-network-prod

networks:
  app-network-prod:
    external: true